name: Ruby Build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build_gem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Set up rake-compiler
        run: gem install rake-compiler

      - name: Build extension
        run: rake compile

      - name: Test run
        run: ruby -Ilib:tmp -r cheetah_qrcode -e "CheetahQRCode.encode('test')"
